<a href="https://colab.research.google.com/github/OWEN-JUN/keras_/blob/master/day0731_colab_keras30_boston_kfold1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
from keras.datasets import boston_housing
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout

(x_train, y_train),(x_test, y_test) = boston_housing.load_data()

print(x_train.shape)
print(x_test.shape)

(404, 13)
(102, 13)


In [46]:
mean = x_train.mean(axis=0)
x_train -= mean
std = x_train.std(axis=0)
x_train /= std

x_test -= mean
x_test /= std
print(x_train)

[[-0.27224633 -0.48361547 -0.43576161 ...  1.14850044  0.44807713
   0.8252202 ]
 [-0.40342651  2.99178419 -1.33391162 ... -1.71818909  0.43190599
  -1.32920239]
 [ 0.1249402  -0.48361547  1.0283258  ...  0.78447637  0.22061726
  -1.30850006]
 ...
 [-0.40202987  0.99079651 -0.7415148  ... -0.71712291  0.07943894
  -0.67776904]
 [-0.17292018 -0.48361547  1.24588095 ... -1.71818909 -0.98764362
   0.42083466]
 [-0.40422614  2.04394792 -1.20161456 ... -1.30866202  0.23317118
  -1.15392266]]


In [0]:
from keras.layers import *
from keras.models import *

def build_model():
  model = Sequential()
  model.add(Dense(64, activation="relu", input_shape=(x_train.shape[1],)))
  model.add(Dense(64, activation="relu"))
  model.add(Dense(1))
  model.compile(optimizer="rmsprop", loss="mse", metrics=["mae"])
  return model


In [0]:

import numpy as np

k=5
num_val_samples = len(x_train)//k
num_epochs = 1
all_scores = []




In [36]:

for i in range(k):
  print("처리중인 폴드 #",i)
  val_data = x_train[i * num_val_samples : (i + 1) * num_val_samples]
  val_targets = y_train[i * num_val_samples : (i + 1) * num_val_samples]

  partial_train_data = np.concatenate([x_train[: i * num_val_samples], x_train[(i + 1) * num_val_samples:]], axis = 0)
  partial_train_targets = np.concatenate([y_train[: i * num_val_samples], y_train[( i + 1 ) * num_val_samples:]], axis = 0)

  model = build_model()
  # model.fit(partial_train_data, partial_train_targets, epochs = num_epochs, batch_size = 1, verbose=1)
  model.fit(partial_train_data, partial_train_targets, epochs=  num_epochs, batch_size= 1, verbose= 0)
  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose = 0)
  all_scores.append(val_mae)


print(all_scores)
print(np.mean(all_scores))










처리중인 폴드 # 0
처리중인 폴드 # 1
처리중인 폴드 # 2
처리중인 폴드 # 3
처리중인 폴드 # 4
[4.011657333374023, 4.434352207183838, 4.449000263214112, 4.174638462066651, 4.752256393432617]
4.364380931854248


In [48]:
gird = np.array([[1, 2, 3], [4, 5, 6]])

gird = np.array([[1, 2, 3], [4, 5, 6]])

# np.concatenate([gird, gird], axis=1)
print(np.concatenate([gird, gird], axis=1))
print(np.concatenate([gird, gird], axis=0))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [67]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4],[5,6]])
y = np.array([0, 0, 1, 1,5])
# skf = StratifiedKFold(n_splits=2)
# skf.get_n_splits(X, y)
# 2


print(skf)  
StratifiedKFold(n_splits=3, random_state=None, shuffle=False)
for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [1 3] TEST: [0 2 4]
TRAIN: [0 2 4] TEST: [1 3]


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=2.
  % (min_groups, self.n_splits)), Warning)
