<a href="https://colab.research.google.com/github/OWEN-JUN/keras_/blob/master/day0731_colab_keras28_lstm_stateful.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np

import keras

from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout, BatchNormalization
from keras.callbacks import *
import matplotlib.pyplot as plt



Using TensorFlow backend.


In [2]:
a = np.array(range(1,101))
batch_size = 1
size = 5

def split_5(seq, size):


    aaa=[]
    for i in range(len(a)-size+1):
        subset = a[i:(i+size)]
        aaa.append(subset)

    print(type(aaa))
    return np.array(aaa)

dataset = split_5(a, size)
print("_____________________________")
print(dataset)
print(dataset.shape)

<class 'list'>
_____________________________
[[  1   2   3   4   5]
 [  2   3   4   5   6]
 [  3   4   5   6   7]
 [  4   5   6   7   8]
 [  5   6   7   8   9]
 [  6   7   8   9  10]
 [  7   8   9  10  11]
 [  8   9  10  11  12]
 [  9  10  11  12  13]
 [ 10  11  12  13  14]
 [ 11  12  13  14  15]
 [ 12  13  14  15  16]
 [ 13  14  15  16  17]
 [ 14  15  16  17  18]
 [ 15  16  17  18  19]
 [ 16  17  18  19  20]
 [ 17  18  19  20  21]
 [ 18  19  20  21  22]
 [ 19  20  21  22  23]
 [ 20  21  22  23  24]
 [ 21  22  23  24  25]
 [ 22  23  24  25  26]
 [ 23  24  25  26  27]
 [ 24  25  26  27  28]
 [ 25  26  27  28  29]
 [ 26  27  28  29  30]
 [ 27  28  29  30  31]
 [ 28  29  30  31  32]
 [ 29  30  31  32  33]
 [ 30  31  32  33  34]
 [ 31  32  33  34  35]
 [ 32  33  34  35  36]
 [ 33  34  35  36  37]
 [ 34  35  36  37  38]
 [ 35  36  37  38  39]
 [ 36  37  38  39  40]
 [ 37  38  39  40  41]
 [ 38  39  40  41  42]
 [ 39  40  41  42  43]
 [ 40  41  42  43  44]
 [ 41  42  43  44  45]
 [ 42  43  4

In [3]:
x_train = dataset[:,0:4]
x_train = x_train.reshape(x_train.shape[0],x_train.shape[1],batch_size)
y_train = dataset[:,4]
print(y_train)
x_test = x_train +100 
y_test = y_train +100




[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94
  95  96  97  98  99 100]


In [8]:


model = Sequential()
model.add(LSTM(4, batch_input_shape=(batch_size,4,1),stateful=True)) #상태유지 stateful
# model.add(BatchNormalization())
model.add(Dense(1,activation="relu"))
model.add(Dense(2,activation="relu"))

# model.add(BatchNormalization())

# model.add(LSTM(128,activation="relu"))
model.add(Dense(1))


hist_loss = []
hist_acc = []
hist_val_loss = []

model.summary()
model.compile(loss="mse", optimizer="adam", metrics=["accuracy"])
num_epochs = 300
# tb_hist = keras.callbacks.TensorBoard(log_dir='./graph', histogram_freq=0, write_graph=True, write_images=True)
early_stopping = EarlyStopping(monitor="loss",patience = 20, mode="auto")


num_epochs = 300
for epoch_idx in range(num_epochs):
  print("epochs:"+str(epoch_idx))
  history=model.fit(x_train, y_train, epochs=num_epochs, batch_size=batch_size, verbose=2, shuffle=False, validation_split=0.2,callbacks=[early_stopping])
  hist_loss.append(history.history["loss"])
  hist_acc.append(history.history["acc"])
  
#   print(hist_loss)
#   print(hist_acc)
#   mse1, acc1= model.evaluate(x_train, y_train, batch_size=1)
  model.reset_states()
#   mse2, acc2= model.evaluate(x_train, y_train, batch_size=1)
#   print(mse1, acc1)
#   print(mse2, acc2)

mse, _= model.evaluate(x_train, y_train, batch_size=batch_size)
print("mse:",mse)
model.reset_states()
y_=model.predict(x_test, batch_size=batch_size)

print(y_[0:10])



from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
def RMSE(y_test, y_):
    return np.sqrt(mean_squared_error(y_test,y_))
def RMAE(y_test, y_):
    return np.sqrt(mean_absolute_error(y_test,y_))
print("RMSE:",RMSE(y_test,y_))
print("RMAE:",RMAE(y_test,y_))

hist_loss = np.array(hist_loss).flatten()
hist_acc = np.array(hist_acc).flatten()
plt.plot(hist_loss)
plt.title("model accuracy")
plt.ylabel("mse")
plt.xlabel("epoch")
plt.legend(["train","test"], loc="upper left")
plt.show()

print(history.history["val_loss"])

#mse <= 1
#rmse
#r2
#earlystop
#tensorboard
#matplotlob :mse/epochs

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_5 (LSTM)                (1, 4)                    96        
_________________________________________________________________
dense_11 (Dense)             (1, 1)                    5         
_________________________________________________________________
dense_12 (Dense)             (1, 2)                    4         
_________________________________________________________________
dense_13 (Dense)             (1, 1)                    3         
Total params: 108
Trainable params: 108
Non-trainable params: 0
_________________________________________________________________
epochs:0
Train on 76 samples, validate on 20 samples
Epoch 1/300
 - 2s - loss: 2256.5372 - acc: 0.0000e+00 - val_loss: 8133.3420 - val_acc: 0.0000e+00
Epoch 2/300
 - 0s - loss: 2212.8332 - acc: 0.0000e+00 - val_loss: 7992.2117 - val_acc: 0.0000e+00
Epoch 3/300
 - 0s - loss: 2

KeyboardInterrupt: ignored