<a href="https://colab.research.google.com/github/OWEN-JUN/keras_/blob/master/day0731_colab_keras30_boston_kfold1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.datasets import boston_housing
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout, BatchNormalization

import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler, MinMaxScaler
(x_train, y_train),(x_test, y_test) = boston_housing.load_data()

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(x_train[0])

Using TensorFlow backend.


57344/57026 [==============================] - 0s 0us/step
(404, 13)
(102, 13)
(404,)
[  1.23247   0.        8.14      0.        0.538     6.142    91.7
   3.9769    4.      307.       21.      396.9      18.72   ]


In [0]:
# stand = StandardScaler()
norm = MinMaxScaler()
# stand.fit(x_train)
# x_train = stand.transform(x_train)
# x_test = stand.transform(x_test)
norm.fit(x_train)
x_train = norm.transform(x_train)
x_test = norm.transform(x_test)

# mean = x_train.mean(axis=0)
# x_train -= mean
# std = x_train.std(axis=0)
# x_train /= std

# x_test -= mean
# x_test /= std
# print(type(x_train))
# print(x_train[0:3])

In [0]:
from keras.layers import *
from keras.models import *

def build_model():
  model = Sequential()
  model.add(Dense(300, activation="relu", input_shape=(x_train.shape[1],)))
  model.add(Dense(500, activation="relu"))

  model.add(Dense(50, activation="relu"))
  model.add(Dense(1))
  model.compile(optimizer="rmsprop", loss="mse", metrics=["mae"])
  return model


In [0]:

import numpy as np

k=4
num_val_samples = len(x_train)//k
num_epochs = 100
all_scores = []
# skf = KFold(n_splits=K)
# for train_index, test_index in skf.split(x_train,y_train):
#     print("TRAIN:", train_index, "TEST:", test_index)
#     x, x_train_test = x_train[train_index], x_train[test_index]
#     y, y_train_test = y_train[train_index], y_train[test_index]

# print(len(x),len(x_train_test))

In [5]:

for i in range(k):
    print("처리중인 폴드 #",i)    
#   val_data = x_train[i * num_val_samples : (i + 1) * num_val_samples]
#   val_targets = y_train[i * num_val_samples : (i + 1) * num_val_samples]

#   partial_train_data = np.concatenate([x_train[: i * num_val_samples], x_train[(i + 1) * num_val_samples:]], axis = 0)
#   partial_train_targets = np.concatenate([y_train[: i * num_val_samples], y_train[( i + 1 ) * num_val_samples:]], axis = 0)
    skf = KFold(n_splits=k)
    for train_index, test_index in skf.split(x_train,y_train):
        # print("TRAIN:", train_index, "TEST:", test_index)
        partial_train_data, val_data = x_train[train_index], x_train[test_index]
        partial_train_targets, val_targets = y_train[train_index], y_train[test_index]
    model = build_model()

    model.fit(partial_train_data, partial_train_targets, epochs = num_epochs, batch_size = 5, verbose=1)
    
    val_mse, val_mae = model.evaluate(x_train_test, y_train_test, verbose = 0)
    all_scores.append(val_mae)


print(all_scores)
print(np.mean(all_scores))










W0731 08:05:46.945249 140667416778624 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0731 08:05:46.988213 140667416778624 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0731 08:05:46.994923 140667416778624 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0731 08:05:47.054355 140667416778624 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.



처리중인 폴드 # 0


W0731 08:05:47.249182 140667416778624 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

W0731 08:05:47.259389 140667416778624 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:973: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.



Epoch 1/100
303/303 [==============================] - 1s 3ms/step - loss: 124.2604 - mean_absolute_error: 7.9211
Epoch 2/100
303/303 [==============================] - 0s 729us/step - loss: 42.2635 - mean_absolute_error: 4.5428
Epoch 3/100
303/303 [==============================] - 0s 728us/step - loss: 32.0258 - mean_absolute_error: 4.0097
Epoch 4/100
303/303 [==============================] - 0s 718us/step - loss: 26.8847 - mean_absolute_error: 3.5526
Epoch 5/100
303/303 [==============================] - 0s 680us/step - loss: 22.7656 - mean_absolute_error: 3.3855
Epoch 6/100
303/303 [==============================] - 0s 679us/step - loss: 22.3600 - mean_absolute_error: 3.2734
Epoch 7/100
303/303 [==============================] - 0s 689us/step - loss: 20.8662 - mean_absolute_error: 3.1632
Epoch 8/100
303/303 [==============================] - 0s 676us/step - loss: 18.7128 - mean_absolute_error: 3.0971
Epoch 9/100
303/303 [==============================] - 0s 688us/step - loss: 18.0

NameError: ignored

In [48]:
gird = np.array([[1, 2, 3], [4, 5, 6]])

gird = np.array([[1, 2, 3], [4, 5, 6]])

# np.concatenate([gird, gird], axis=1)
print(np.concatenate([gird, gird], axis=1))
print(np.concatenate([gird, gird], axis=0))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [29]:
import numpy as np
from sklearn.model_selection import KFold
# X = np.array([[1.2, 2,3], [3, 4,3], [1, 2,3], [3, 4,3],[5,6,3]])
# print(X.shape)
# print(X[0])
# y = np.array([0, 0, 1, 1,5])
# skf = StratifiedKFold(n_splits=2)
# skf.get_n_splits(X, y)
# 2

print(y_train.shape)
# # print(skf)  
skf = KFold(n_splits=3)
for train_index, test_index in skf.split(x_train,y_train):
    print("TRAIN:", train_index, "TEST:", test_index)
    # x_train, x_test = X[train_index], X[test_index]
    # y_train, y_test = y[train_index], y[test_index]


# kf = KFold(n_splits=3) 
# for index_kf_train, index_kf_validation in kf.split(x_train):
#     print('index_kf_train:', index_kf_train)
#     print('index_kf_validation:', index_kf_validation)

(3,)


ValueError: ignored