<a href="https://colab.research.google.com/github/OWEN-JUN/keras_/blob/master/day0802_colab_keras35_lstm_mlp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# -*- coding: utf-8 -*-
"""day0802_colab_keras35_lstm_mlp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jHYOiQ4NHbAlSm2lZpVP8qwXACk67x3y
"""

import numpy as np
from keras.models import Sequential
from keras.layers import Dense, LSTM
# from sklearn import standard



x = np.array(range(1,101))
print(x)

size = 8

def split_5(seq, size):


    aaa=[]
    for i in range(len(seq)-size+1):
        subset = seq[i:(i+size)]
        aaa.append(subset)

    print(type(aaa))
    return np.array(aaa)


dataset=split_5(x, size)
print("==================")


print(dataset)
x = dataset[:,:-4]
y = dataset[:,-4:]
# print(x)
print(x.shape)
# print(y)
print(y.shape)

x = x.reshape(x.shape[0],-1,2)
print(x)



[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
<class 'list'>
[[  1   2   3   4   5   6   7   8]
 [  2   3   4   5   6   7   8   9]
 [  3   4   5   6   7   8   9  10]
 [  4   5   6   7   8   9  10  11]
 [  5   6   7   8   9  10  11  12]
 [  6   7   8   9  10  11  12  13]
 [  7   8   9  10  11  12  13  14]
 [  8   9  10  11  12  13  14  15]
 [  9  10  11  12  13  14  15  16]
 [ 10  11  12  13  14  15  16  17]
 [ 11  12  13  14  15  16  17  18]
 [ 12  13  14  15  16  17  18  19]
 [ 13  14  15  16  17  18  19  20]
 [ 14  15  16  17  18  19  20  21]
 [ 15  16  17  18  19  20  21  22]
 [ 16  17  18  19  20  21  22  23]
 [ 17  18  19  20 

In [0]:

# x_test = np.array([[[11],
#   [12],
#   [13],
#   [14]],

#  [[12],
#   [13],
#   [14],
#   [15]],

#  [[13],
#   [14],
#   [15],
#   [16]],

#  [[14],
#   [15],
#   [16],
#   [17]],

#  [[15],
#   [16],
#   [17],
#   [18]],

#  [[16],
#   [17],
#   [18],
#   [19]]])

# y_test = np.array([15, 16, 17, 18, 19, 20])

# print(x.shape)
# print(y.shape)
# print(x_test.shape)
# print(y_test.shape)


x_test = x
y_test = y
#모델구성

model = Sequential()

model.add(LSTM(32, input_shape=(2,2),return_sequences=True))


model.add(LSTM(10))

model.add(Dense(5, activation="relu"))
model.add(Dense(3))
model.add(Dense(4))
model.summary()
model.compile(loss = "mse",optimizer="adam", metrics=['accuracy'])
from keras.callbacks import EarlyStopping
early = EarlyStopping(monitor="loss", patience=300, mode="auto")
model.fit(x,y,epochs=3000, callbacks=[early])

loss, acc = model.evaluate(x_test, y_test)
y_ = model.predict(x_test)
print(y_, "ori: ",y_test)
print(loss, acc)
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error
def RMSE(y_test, y_):
    return np.sqrt(mean_squared_error(y_test,y_))
def RMAE(y_test, y_):
    return np.sqrt(mean_absolute_error(y_test,y_))
print("RMSE:",RMSE(y_test,y_))
print("RMAE:",RMAE(y_test,y_))
print("r2:",r2_score(y_test,y_))



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_4 (LSTM)                (None, 2, 32)             4480      
_________________________________________________________________
lstm_5 (LSTM)                (None, 10)                1720      
_________________________________________________________________
dense_4 (Dense)              (None, 5)                 55        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 18        
_________________________________________________________________
dense_6 (Dense)              (None, 4)                 16        
Total params: 6,289
Trainable params: 6,289
Non-trainable params: 0
_________________________________________________________________


W0802 03:18:12.056072 140516605794176 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0802 03:18:13.334650 140516605794176 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

W0802 03:18:13.501157 140516605794176 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:973: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.



Epoch 1/3000
93/93 [==============================] - 2s 17ms/step - loss: 3479.4703 - acc: 0.0000e+00
Epoch 2/3000
93/93 [==============================] - 0s 222us/step - loss: 3478.7279 - acc: 0.0108
Epoch 3/3000
93/93 [==============================] - 0s 216us/step - loss: 3477.9863 - acc: 0.0215
Epoch 4/3000
93/93 [==============================] - 0s 250us/step - loss: 3477.3245 - acc: 0.1505
Epoch 5/3000
93/93 [==============================] - 0s 215us/step - loss: 3476.6659 - acc: 0.9570
Epoch 6/3000
93/93 [==============================] - 0s 211us/step - loss: 3476.0572 - acc: 1.0000
Epoch 7/3000
93/93 [==============================] - 0s 220us/step - loss: 3475.4935 - acc: 1.0000
Epoch 8/3000
93/93 [==============================] - 0s 219us/step - loss: 3475.0260 - acc: 1.0000
Epoch 9/3000
93/93 [==============================] - 0s 224us/step - loss: 3474.5469 - acc: 1.0000
Epoch 10/3000
93/93 [==============================] - 0s 264us/step - loss: 3474.0586 - acc: 1.0